sudo: required

services:
  - docker

before_install:
  - docker build -t ogandoe/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ogandoe/react-test npm run test

after_success:
  - docker build -t ogandoe/multi-client  ./client
  - docker build -t ogandoe/multi-nginx ./nginx
  - docker build -t ogandoe/multi-server  ./server
  - docker build -t ogandoe/multi-worker  ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ogandoe/multi-client
  - docker push ogandoe/multi-nginx
  - docker push ogandoe/multi-server
  - docker push ogandoe/multi-worker

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-sa-east-1-347061874496
  bucket_path: docker-multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
